/*
/* 
 * File:   main.cpp
 * Author: Thu Pham
 * Created on January 4, 2024, 11:28 PM
 * Purpose: Sales Prediction
 */

//System Libraries
#include <iostream> //Input-Output Library
using namespace std;

//User Libraries

//Global Constants - Math,Physics.Chemistry.Conversions

//Function Prototypes

//Program Execution Begins Here
int main(int argc, char** argv) {
    
//Declare all variables

//Initialize all variables
float Percent = .58,    //Total Sales
      SaleGen = 8.6e6,  //Sales generated by East Coast this year
      TotSale;  

//Process or Map solutions
TotSale = Percent * SaleGen;

//Display the output
cout<<"The East Coast will generate "<<TotSale<<" in sales this year"<<endl;
    
//Exit the Program
    return 0;
}


